<a href="https://colab.research.google.com/github/jakubdaron/data_science_course_udemy/blob/main/Uczenie_glebokie/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Model sekwencyjny (Sequential Model)**

Załadowanie biblioteki tensorflow

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.13.0'

Wprowadzenie - pierwszy model

Model sekwencyjny to nic innego jak liniowy stos warst

In [2]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody .add()

In [4]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

Wyświetlenie podsumowania modelu: metoda .summary()

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
Total params: 44 (176.00 Byte)
Trainable params: 44 (176.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Dodanie kolejnej warstwy

In [7]:
model.add(Dense(units=2))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54 (216.00 Byte)
Trainable params: 54 (216.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Funkcje aktywacji

Istotnym elementem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. a(x) = x

Warstwa z liniowa funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiązać problemy nieliniowe

In [9]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [10]:

px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [11]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [12]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [13]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [14]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])


In [15]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [16]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [17]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97 (388.00 Byte)
Trainable params: 97 (388.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Kompilacja modelu

In [18]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

Trenowanie modelu

Za dane wejściowe do modelu należy przekazać Numpy arrays:
- **epochs** - krotność przejścia danych przez sieć w procesie uczenia
- **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
- **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
- **validation_data** - (x_val,y_val) - dane wykorzystane do walidacji modelu

In [19]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

Przykład - klasyfikacja binarna

In [20]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [21]:
data[:3]

array([[-5.19130639e-01,  2.61108262e-01, -1.08639018e+00,
         1.02078970e-01, -1.32402988e+00,  2.22912925e+00,
        -1.04020329e+00,  7.36013475e-01,  2.43927259e+00,
         9.87411877e-01,  1.90896802e-01, -1.21527328e+00,
        -3.48360596e-01, -1.34996696e-01,  5.71402731e-02,
         1.50195183e+00, -1.10280965e-01,  7.91206216e-02,
         1.95855247e+00, -9.67316010e-01, -1.50858768e+00,
        -1.80157398e+00, -5.92056697e-03,  1.84772115e+00,
        -8.00486303e-01, -2.54416991e-01,  1.70548896e-01,
         4.21117927e-02, -1.11389389e+00,  8.17915192e-01,
         4.05912959e-01, -1.85468735e-01,  5.86355759e-02,
         3.64182816e-02, -1.12312476e+00, -3.09373041e-01,
        -8.82722767e-01, -6.57820762e-02,  2.13741734e-01,
         4.17423754e-01, -2.74147587e-01,  1.02194676e-01,
        -1.59398936e+00, -1.15801672e+00, -2.03552071e+00,
         6.01506953e-01, -1.69244075e+00, -1.40502154e-01,
         2.90852104e-01,  6.58034076e-01,  2.53107491e-0

In [22]:
labels[:10]

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0]])

In [23]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 2s 2ms/step - loss: 0.7695 - accuracy: 0.4975
Epoch 2/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6962 - accuracy: 0.5416
Epoch 3/20
313/313 [==============================] - 1s 4ms/step - loss: 0.6767 - accuracy: 0.5756
Epoch 4/20
313/313 [==============================] - 1s 3ms/step - loss: 0.6620 - accuracy: 0.6041
Epoch 5/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6480 - accuracy: 0.6252
Epoch 6/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6338 - accuracy: 0.6432
Epoch 7/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6198 - accuracy: 0.6644
Epoch 8/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6056 - accuracy: 0.6725
Epoch 9/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5910 - accuracy: 0.6936
Epoch 10/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5781 - accuracy: 0.7061

In [24]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20
157/157 [==============================] - 1s 2ms/step - loss: 0.7537 - accuracy: 0.5064
Epoch 2/20
157/157 [==============================] - 0s 2ms/step - loss: 0.7018 - accuracy: 0.5312
Epoch 3/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6840 - accuracy: 0.5584
Epoch 4/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6720 - accuracy: 0.5851
Epoch 5/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6612 - accuracy: 0.6065
Epoch 6/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6514 - accuracy: 0.6206
Epoch 7/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6412 - accuracy: 0.6332
Epoch 8/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6312 - accuracy: 0.6530
Epoch 9/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6213 - accuracy: 0.6609
Epoch 10/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6110 - accuracy: 0.6732

In [25]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
250/250 [==============================] - 1s 3ms/step - loss: 0.7429 - accuracy: 0.4938 - val_loss: 0.7252 - val_accuracy: 0.4810
Epoch 2/20
250/250 [==============================] - 1s 4ms/step - loss: 0.6918 - accuracy: 0.5469 - val_loss: 0.7241 - val_accuracy: 0.4945
Epoch 3/20
250/250 [==============================] - 1s 4ms/step - loss: 0.6716 - accuracy: 0.5825 - val_loss: 0.7248 - val_accuracy: 0.4900
Epoch 4/20
250/250 [==============================] - 1s 4ms/step - loss: 0.6555 - accuracy: 0.6194 - val_loss: 0.7298 - val_accuracy: 0.5025
Epoch 5/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6402 - accuracy: 0.6407 - val_loss: 0.7339 - val_accuracy: 0.4945
Epoch 6/20
250/250 [==============================] - 1s 3ms/step - loss: 0.6237 - accuracy: 0.6637 - val_loss: 0.7371 - val_accuracy: 0.5050
Epoch 7/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6073 - accuracy: 0.6841 - val_loss: 0.7472 - val_accuracy: 0.5145
Epoch 

In [27]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [28]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [29]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [34]:
model.predict(test_data)


1/1 [==============================] - 0s 30ms/step


array([[0.9081781 ],
       [0.01782644],
       [0.35944036],
       [0.09666939],
       [0.4181085 ]], dtype=float32)

In [39]:
predictions = (model.predict(test_data) > 0.5).astype("int32")
predictions

1/1 [==============================] - 0s 34ms/step


array([[1],
       [0],
       [0],
       [0],
       [0]], dtype=int32)