<a href="https://colab.research.google.com/github/jakubdaron/data_science_course_udemy/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Podstawy**

In [1]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [7]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [11]:
x.shape

(2,)

In [12]:
x.size

2

In [13]:
x.dtype

dtype('int64')

In [15]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [16]:
x.dtype

dtype('float64')

2D Array

In [18]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [19]:
x.ndim


2

In [20]:
x.shape

(2, 2)

In [21]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [22]:
x.shape


(2, 3)

3D Array

In [23]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

    [[4,1,3],
     [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [24]:
x.ndim

3

In [25]:
x.shape

(2, 2, 3)