<a href="https://colab.research.google.com/github/jakubdaron/data_science_course_udemy/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Podstawy**

In [1]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [7]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [11]:
x.shape

(2,)

In [12]:
x.size

2

In [13]:
x.dtype

dtype('int64')

In [15]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [16]:
x.dtype

dtype('float64')

2D Array

In [18]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [19]:
x.ndim


2

In [20]:
x.shape

(2, 2)

In [21]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [22]:
x.shape


(2, 3)

3D Array

In [23]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

    [[4,1,3],
     [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [24]:
x.ndim

3

In [25]:
x.shape

(2, 2, 3)

Typy danych

In [26]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [27]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [31]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [32]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [33]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

dtype('int64')

In [34]:
A

array([1, 2, 3])

In [35]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [36]:
A = np.array([24,128,230], dtype=np.int8)
A.dtype

dtype('int8')

In [38]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic

In [39]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [41]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [47]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [49]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [51]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [52]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [56]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [57]:
A + B

array([6, 0, 7, 4])

In [58]:
A - B

array([0, 2, 1, 0])

In [59]:
A * B

array([ 9, -1, 12,  4])

In [60]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [64]:
np.add(A, B)

array([6, 0, 7, 4])

In [65]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [66]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [67]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [61]:
A + 3


array([6, 4, 7, 5])

In [62]:
2 * A

array([6, 2, 8, 4])

In [63]:
A + 3*B

array([12, -2, 13,  8])

In [70]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [71]:
X * Y

array([[6, 0],
       [2, 0]])

In [72]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [73]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [74]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [76]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [77]:
np.random.seed(0)

In [82]:
np.random.randn(10)

array([-0.35955316, -0.81314628, -1.7262826 ,  0.17742614, -0.40178094,
       -1.63019835,  0.46278226, -0.90729836,  0.0519454 ,  0.72909056])

In [80]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [84]:
np.random.rand()

0.6674103799636817

In [85]:
np.random.rand(10)

array([0.13179786, 0.7163272 , 0.28940609, 0.18319136, 0.58651293,
       0.02010755, 0.82894003, 0.00469548, 0.67781654, 0.27000797])

In [86]:
np.random.rand(10, 2)

array([[0.73519402, 0.96218855],
       [0.24875314, 0.57615733],
       [0.59204193, 0.57225191],
       [0.22308163, 0.95274901],
       [0.44712538, 0.84640867],
       [0.69947928, 0.29743695],
       [0.81379782, 0.39650574],
       [0.8811032 , 0.58127287],
       [0.88173536, 0.69253159],
       [0.72525428, 0.50132438]])

In [87]:
np.random.randint(10)

3

In [89]:
np.random.randint(low=10, high=101, size=10)

array([42, 80, 95, 41, 23, 81, 66, 34, 89, 51])

In [97]:
np.random.choice([4, 2, 1, 3])

2

In [99]:
np.random.choice(['python', 'java', 'sql'])

'java'

In [101]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
np.random.shuffle(data)


In [108]:
data

array([6, 4, 0, 7, 3, 5, 2, 8, 1, 9])

Podstawowe funkcje

In [109]:
np.exp(1)

2.718281828459045

In [110]:
np.sqrt(9)

3.0

In [112]:
np.all([2, 3, 0])

False

In [114]:
np.any([0, 0, 0])

False

In [117]:
bool(1.3)

True

In [119]:
A = np.random.rand(5)
A


array([0.97552151, 0.85580334, 0.01171408, 0.35997806, 0.72999056])

In [120]:
np.argmax(A)

0

In [121]:
A[np.argmax(A)]

0.9755215050028858

In [122]:
np.argmin(A)

2

In [123]:
np.argsort(A)

array([2, 3, 4, 1, 0])

In [124]:
np.max(A)

0.9755215050028858

In [125]:
np.min(A)

0.011714084185001972

In [126]:
np.mean(A)

0.5866015116965841

In [127]:
np.median(A)

0.729990562424058

In [128]:
np.std(A)

0.3538764043707764