<a href="https://colab.research.google.com/github/jakubdaron/data_science_course_udemy/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.23.5'

Norma wektora, długość wektora

In [5]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [6]:
np.linalg.norm(v1)

4.123105625617661

Norma euklidesowa

In [7]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [8]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

Odległość dwóch punktów w przestrzeni Rn

In [9]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

Mnożenie macierzy

In [10]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X)
print(Y)


[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [11]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [12]:
Z.shape

(2, 1)

In [14]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [15]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [18]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

Ślad macierzy (suma elementów na przekątnej macierzy)

In [19]:
np.trace(A)

5

Macierz jednostkowa

In [20]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Macierz odwrotna

In [22]:
A

array([[ 2,  4],
       [-1,  3]])

In [23]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [25]:
np.set_printoptions(precision=4, suppress=True)

print(np.dot(A, B))

print(np.dot(B, A))

[[1. 0.]
 [0. 1.]]
[[ 1. -0.]
 [ 0.  1.]]


Macierz transponowana

In [26]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [27]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [31]:
A = np.array([[2 ,4], [1, -1]])
B = np.array([[10], [-1]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [32]:
X.shape

(2, 1)